name: Deploy to Production

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    workflow_dispatch:
    push:
        branches:
            - ci-improvements

jobs:
    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download dependencies
              run: |
                  yarn install
                  yarn prisma generate

            - name: Install Turso CLI
              env:
                  TURSO_INSTALL_SKIP_SIGNUP: true
              run: |
                  curl -sSfL https://get.tur.so/install.sh | bash
                  echo "PATH=$PATH:/home/runner/.turso" >> $GITHUB_ENV

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Set APP_VERSION
              shell: bash
              run: |
                  VERSION=$(grep -E '^APP_VERSION=' .vercel/.env.production.local | cut -d '=' -f 2)

                  VERSION_ARRAY=(${VERSION//./ })

                  # Get the first three numbers in the version
                  YEAR=${VERSION_ARRAY[0]}
                  MONTH=${VERSION_ARRAY[1]}
                  DAY=${VERSION_ARRAY[2]}
                  PATCH=${VERSION_ARRAY[3]}

                  # Get the current year, month, and day
                  CURRENT_YEAR=$(date +%Y)
                  CURRENT_MONTH=$(date +%-m)
                  CURRENT_DAY=$(date +%-d)

                  # Check if the major, minor, and patch version numbers match the current date
                  if [[ "$YEAR" == "$CURRENT_YEAR" && "$MONTH" == "$CURRENT_MONTH" && "$DAY" == "$CURRENT_DAY" ]]; then
                    PATCH=$((PATCH+1))
                  else
                    PATCH=0
                  fi

                  echo "APP_VERSION=${CURRENT_YEAR}.${CURRENT_MONTH}.${CURRENT_DAY}.${PATCH}" >> $GITHUB_ENV

            - name: Apply Database Migrations
              env:
                  TURSO_DATABASE_NAME: ${{ secrets.TURSO_PROD_DATABASE_NAME }}
                  TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
              run: ./.github/scripts/turso-migrate.sh

            - name: Update Vercel Environment Information
              run: |
                  vercel env rm APP_VERSION production --yes --token=${{ secrets.VERCEL_TOKEN }}
                  echo "$APP_VERSION" | vercel env add APP_VERSION production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Create Tag
              run: |
                  TAG_NAME="v$APP_VERSION"
                  COMMIT_SHA="${{ github.sha }}"
                  OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
                  REPO=$(echo "${{ github.repository }}" | cut -d '/' -f 2)

                  curl -X POST \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/$OWNER/$REPO/git/refs" \
                    -d "{\"ref\":\"refs/tags/$TAG_NAME\",\"sha\":\"$COMMIT_SHA\",\"tagger\":{\"name\":\"${{ github.actor }}\",\"email\":\"${{ github.actor }}@users.noreply.github.com\",\"date\":\"$(date --iso-8601=seconds)\"}}"

            - name: Deploy Project to Vercel
              run: curl -X POST ${{ secrets.VERCEL_PROD_DEPLOYMENT_HOOK }}
