name: Formating

on: [push]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16.17"
            - name: Install dependencies
              run: npm install
            - name: Run Prettier
              run: npm run format:check
