on:
    pull_request:
        branches-ignore:
            - main

jobs:
    tsc:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "install"
              run: yarn install

            - name: "lint"
              run: yarn lint --max-warnings=0
