on:
    pull_request:
        branches-ignore:
            - main

jobs:
    tsc:
        name: Migrate Diff
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "install"
              run: yarn install

            - name: "migrate:diff"
              run: yarn migrate:diff
