name: Simulate Migration
on:
    push:
    workflow_dispatch:

concurrency:
    group: ${{ github.sha }}
    cancel-in-progress: false

env:
    TURSO_INSTALL_SKIP_SIGNUP: true
    TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}

jobs:
    check-migrations:
        name: Check migrations
        runs-on: ubuntu-latest
        outputs:
            simulation-needed: ${{ steps.set-output.outputs.simulation-needed }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Download dependencies
              run: |
                  yarn install --frozen-lockfile
                  yarn prisma generate

            - name: Install Turso CLI
              run: |
                  curl -sSfL https://get.tur.so/install.sh | bash
                  echo "PATH=$PATH:/home/runner/.turso" >> $GITHUB_ENV

            - name: Dry Run Database Migrations
              env:
                  TURSO_DATABASE_NAME: "staging"
              run: |
                  ./.github/scripts/turso-migrate.sh --dry
                  if [ $TURSO_PENDING_MIGRATIONS -gt 0 ]; then
                      echo "simulation-needed=true" >> $GITHUB_OUTPUT
                  else
                      echo "simulation-needed=false" >> $GITHUB_OUTPUT
                  fi

    simulate-migrations:
        needs: check-migrations
        if: needs.check-migrations.outputs.migration-needed == 'true'
        name: Simulate migrations
        runs-on: ubuntu-latest
        env:
            TURSO_NEW_DATABASE_NAME: ${{ github.sha }}
            TURSO_PARENT_DATABASE_NAME: "staging"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Download dependencies
              run: |
                  yarn install --frozen-lockfile
                  yarn prisma generate

            - name: Install Turso CLI
              run: |
                  curl -sSfL https://get.tur.so/install.sh | bash
                  echo "PATH=$PATH:/home/runner/.turso" >> $GITHUB_ENV

            - name: Create Temp Database
              run: |
                  turso --version
                  turso db create $TURSO_NEW_DATABASE_NAME --from-db $TURSO_PARENT_DATABASE_NAME --wait

            - name: Dry Run Database Migrations
              env:
                  TURSO_DATABASE_NAME: ${{ env.TURSO_NEW_DATABASE_NAME }}
              run: |
                  ./.github/scripts/turso-migrate.sh

            - name: Cleanup Temp Database
              run: |
                  turso --version
                  turso db destroy $TURSO_NEW_DATABASE_NAME --yes
