name: Static Pull Request Checks
on:
    pull_request:
        branches:
            - main

jobs:
    common-setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: yarn install

    tsc:
        runs-on: ubuntu-latest
        needs: common-setup
        steps:
            - name: "tsc"
              run: yarn tsc

    lint:
        runs-on: ubuntu-latest
        needs: common-setup
        steps:
            - name: "eslint"
              run: yarn lint --max-warnings=0

    format:
        name: Formatting
        runs-on: ubuntu-latest
        needs: common-setup
        steps:
            - name: "format:check"
              run: yarn format:check

    migrate-drift:
        name: Migrate Drift
        runs-on: ubuntu-latest
        needs: common-setup
        steps:
            - name: "migrate:drift"
              run: yarn migrate:drift
