name: Static Pull Request Checks
on:
    pull_request:
        branches:
            - main

jobs:
    tsc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: "tsc"
              run: bun tsc

    format:
        name: Formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: "format:check"
              run: bun format:check

    lint:
        runs-on: ubuntu-latest
        needs: ["tsc", "format"]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: "eslint"
              run: bun lint --max-warnings=0

    migrate-drift:
        name: Migrate Drift
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: "migrate:drift"
              run: bun migrate:drift
